## Tarea 2: Loops
## Profesor: Rafael Dávila Bugarín
## Clase: Introducción a Ciencia de Datos



Descargue este notebook en su computadora y resuelva los siguientes ejercicios:<br>

1. En su código tiene que usar la fución <strong>input()</strong> que tenga como input un entero <strong>n</strong>, posteriormente para todo entero no negativo $i<n$ imprime en una línea distinta $i^2$. Ejemplo: $n=3$, $[0,1,2]$ imprime:<br>
0<br>
1<br>
4<br>

Este ejercicio es recogido de [hackerrank](https://www.hackerrank.com/).


2. Imprime los números impares del 1 a 20 que no sean divisibles por 3, <strong>hint</strong>: usen el operador modulo <strong>%</strong> que arroja el residuo de la división de 2 números A%B, ejemplo 17%3=2 porque 5*3=15 y 17-15=2.

### El ejercicio 3 es opcional pero recomendado

3. Crear una matriz nxn con n={2,5,10} que vaya de uno en uno la 
primer fila, de 2 en 2 la segunda y así sucesivamente y con el primer elemento
de cada fila conectado con el último por diferencia de 1. Este ejercicio ocupará [matrices](https://www.programiz.com/python-programming/matrix)
    

Ejemplo n=2    

$$
\begin{bmatrix}
1 & 2  \\
3 & 5 
\end{bmatrix}
$$


Ejemplo n=3

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 6 & 8 \\
9 & 12 & 15
\end{bmatrix}
$$

In [30]:
# Ejercicio 1
import math
while(True):
    try:
        n = int(input("Ingresa un número entero: "))
        break
    except:
        print("Numero entero no valido");
for i in range(n):
    print(int(math.pow(i,2)))

Ingresa un número entero: 3
0
1
4


In [35]:
# Ejercicio 2
for i in range(1,21):
    if i%2 == 1 and i%3 != 0:
        print(i)

1
5
7
11
13
17
19


In [29]:
# Ejercicio 3
import numpy as np
import math

for n in [2, 5, 10]:
    elems = np.array([])
    cont = 0
    
    for elem in range(int(math.pow(n, 2))):
        if elem%n == 0: # if we start a new row increment by one
            cont +=1 
        else:            # else we increment by the row number (starting on 1)
            cont += (elem//n) + 1
        elems = np.append(elems, cont)
        
    mat = np.array(elems).reshape(n, n)    
    print(mat)

print("\n--With Nested loops--\n")
for n in [2, 5, 10]:
    elems = np.array([])
    cont = 0
    
    for row in range(1, n+1):   # set row to start on 1
        new_row = np.array([])
        cont += 1               # at start of new row increment by one
        new_row = np.append(new_row, cont)
        for col in range(1,n):  # the first col is set, so go from 2 to n
            cont += row         # all cols except first will increment by row number
            new_row = np.append(new_row, cont)
        elems = np.append(elems, new_row);
    mat = np.array(elems).reshape(n, n)    
    print(mat)

[[1. 2.]
 [3. 5.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  8. 10. 12. 14.]
 [15. 18. 21. 24. 27.]
 [28. 32. 36. 40. 44.]
 [45. 50. 55. 60. 65.]]
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  13.  15.  17.  19.  21.  23.  25.  27.  29.]
 [ 30.  33.  36.  39.  42.  45.  48.  51.  54.  57.]
 [ 58.  62.  66.  70.  74.  78.  82.  86.  90.  94.]
 [ 95. 100. 105. 110. 115. 120. 125. 130. 135. 140.]
 [141. 147. 153. 159. 165. 171. 177. 183. 189. 195.]
 [196. 203. 210. 217. 224. 231. 238. 245. 252. 259.]
 [260. 268. 276. 284. 292. 300. 308. 316. 324. 332.]
 [333. 342. 351. 360. 369. 378. 387. 396. 405. 414.]
 [415. 425. 435. 445. 455. 465. 475. 485. 495. 505.]]

--With Nested loops--

[[1. 2.]
 [3. 5.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  8. 10. 12. 14.]
 [15. 18. 21. 24. 27.]
 [28. 32. 36. 40. 44.]
 [45. 50. 55. 60. 65.]]
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  13.  15.  17.  19.  21.  23.  25.  27.  29.]
 [ 30.  33.  36.  39.  42.  45.  48.  51.  54.  57.]
 [ 58.  62.  66.