In [1]:
## Mitsiu Alejandro Carreño Sarabia - E23S-18014
### Ejercicio 5.1 - Rangos

import numpy as np

A = np.array([
      [-14,16,-2,14,-18],
      [-8, -13, -16, -10, -8],
      [2,0,12,-1,2],
      [11,19,8,-3,-19],
      [6,95,0,7,-122]
    ])

b = np.array([318, 51, -46, -376, -771]).reshape(len(A), 1)

print(f"Rango A: {np.linalg.matrix_rank(A)}")
print(f"Rango B: {np.linalg.matrix_rank(np.concatenate([A,b], 1))}")

# Tanto el rango de A como de B son iguales por lo que sabemos que el sistema es consistente y tiene solución
# Los rangos son menores que el número de columnas de A, por ello sabemos que uno de los vectores es linealmente dependiente 
# Por ello sabemos que A y b tienen soluciones infinitas
sol_a = np.linalg.solve(A, b)
sol_b, res, rank, s = np.linalg.lstsq(A, b, rcond=None)

print(sol_a)
print(np.matmul(A, sol_a) - b < 0.000000000001 )
print(sol_b)
print(np.matmul(A, sol_b) - b < 0.000000000001)

Rango A: 4
Rango B: 4
[[ -7.68009518]
 [-17.34339914]
 [  0.71696216]
 [ 27.24335557]
 [ -6.        ]]
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]]
[[-18.65046596]
 [ -3.70491095]
 [ -0.22840211]
 [ 12.41821249]
 [  3.22998485]]
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]]


In [2]:
### Ejercicio 5.2 - Matriz mal condicionada
mA = (np.random.randint(20, size=(6,6))).astype(float)
mx = (np.random.randint(20, size=(6,1))).astype(float)
mb = np.matmul(mA, mx)
# En este punto tenemos un sistema correcto


# Aqui vamos a modificar ligeramente un valor para que sea muy cercano a un valor correcto, pero no igual
mA[-1] = mA[0]*2
mA[-1][0] += 0.0000001

mmx = np.linalg.solve(mA, mb)
print(mx)
print (np.matmul(mA, mmx) - mb)

## La diferencia que vemos entre los valores reales (mx) y los valores con la matriz mal condicionada (mmx) superan el rango de los provocados por error de precisión flotante que usualmente estan en e-13

[[15.]
 [ 2.]
 [ 5.]
 [ 2.]
 [ 0.]
 [11.]]
[[-1.52587891e-05]
 [-1.52587891e-05]
 [-6.10351562e-05]
 [ 0.00000000e+00]
 [-3.05175781e-05]
 [-3.05175781e-05]]
