In [29]:
## Mitsiu Alejandro Carreño Sarabia - E23S-18014
### Ejercicio 2 - Descomposición LU

import numpy as np
import scipy

A = np.array([[-7., 1., -2.],[2., -3., 1.],[9., -3., -6.]])
b = np.array([28., 14., 84.])

# Descomponer la matriz A en sus componentes LU
L, U = scipy.linalg.lu(A, True)
print(f"L {L}\n\n U {U}")

# Una vez obtenidas las matrices L y U, resolvemos el sistema de ecuaciones de c = L | B  
c = np.linalg.solve(L, b)
# Con el resultado anterior podemos obtener los valores de nuestras incognitas resolviendo el sistema  U | c
x = np.linalg.solve(U, c)

print("Resultado de x")
print(x)

# Corroboramos el resultado
print(np.matmul(A, x) -b)

L [[-0.77777778  0.57142857  1.        ]
 [ 0.22222222  1.          0.        ]
 [ 1.          0.          0.        ]]

 U [[ 9.         -3.         -6.        ]
 [ 0.         -2.33333333  2.33333333]
 [ 0.          0.         -8.        ]]
Resultado de x
[ -2. -10. -12.]
[ 1.42108547e-14 -5.32907052e-15  0.00000000e+00]
