# Matriz inversa 

En este documento vemos algunos ejemplos de cómo obtener la matriz inversa

Solo haremos uso de numpy. La librería tqdm (no se confunda con te quiero demasiado) nos permite mostrar el progreso de ciclos 

In [10]:
import numpy as np
!pip install pip install tqdm
from tqdm.notebook import tqdm

Defaulting to user installation because normal site-packages is not writeable


Nos apoyamos en la definición anterior del método de Gauss-Jordan ahora para calcular la inversa

In [51]:
def imprimir_sistema(matriz_coeficientes,matriz_inversa):
  n_filas, n_columnas= matriz_coeficientes.shape
  for fila, fila_inv in zip(matriz_coeficientes,matriz_inversa):
    fila_formato = "\t".join([f"{x: 4.2f}" for x in fila])
    fila_inv_formato = "\t".join([f"{x: 4.2f}" for x in fila_inv])
    print(f"{fila_formato}|{fila_inv_formato}")

def inversa_gauss_jordan(matriz_coeficientes):
  matriz = matriz_coeficientes.astype(float)
  n_filas, n_columnas= matriz.shape
  inversa = np.eye(n_filas)
  #for columna in tqdm(range(n_columnas)):
  for columna in range(n_columnas):
    #print(f"Columna {columna}")
    for fila in range(n_filas):
      #print(f"Fila {fila}")
      if  fila == columna:
        factor = 1/matriz[fila,columna] 
        matriz[fila,:] = matriz[fila,:] * factor
        inversa[fila,:] = inversa[fila,:] * factor 
        #imprimir_sistema(matriz,inversa)
      else:
        factor = - matriz[fila,columna] / matriz[columna,columna]
        #print(f"factor de {factor} ")
        #print(f"R{fila} --> {factor}*R{columna} + R{fila}") 
        matriz[fila,:] = matriz[columna,:] * factor + matriz[fila,:]
        inversa[fila,:] = inversa[columna,:] * factor + inversa[fila,:]
        #imprimir_sistema(matriz,inversa)

  return inversa

Definimos el tamaño de la matriz, y generamos una matriz aleatoria 

In [46]:
n = 10

In [18]:
A = np.random.randint(-20, 20, size=(n,n))
A

array([[ -8,  -1,   2,  -8,  12,  18,  -8, -18,  -2,   7],
       [ -9,   8, -11,  12,  11, -11,   2,  -3,  11,  15],
       [-12,   8, -19,  11,   2,   8, -18,   8,  13,  10],
       [-20,   5,   6, -12,   9,  18, -15,  14,  -1,   9],
       [  8,  10,  -3, -16,  -3, -13,  12,  11,  -2, -17],
       [ 19, -10, -12,  -8,  15,  -4,  13,  -6, -20,  -8],
       [  7,  17, -11, -12,   7,  17,  17, -13,   4,  -3],
       [-12,   5, -17,  16,  10, -11,  10,  16,   7,   5],
       [ 13,  -4,  10,  16, -10, -14,  12,   0, -11,  -7],
       [-12,  13, -14,   3, -20,   4,  -7,   8,   9,   2]])

Calaculamos el determinante para ver si es invertible.

In [19]:
np.linalg.det(A)

25398326747879.99

Calculamos la inversa con nuestro método y mostramos el resultado.

In [20]:
A_inv = inversa_gauss_jordan(A)
A_inv

Columna 0
Fila 0
 1.00	 0.12	-0.25	 1.00	-1.50	-2.25	 1.00	 2.25	 0.25	-0.88|-0.12	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00
-9.00	 8.00	-11.00	 12.00	 11.00	-11.00	 2.00	-3.00	 11.00	 15.00| 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00
-12.00	 8.00	-19.00	 11.00	 2.00	 8.00	-18.00	 8.00	 13.00	 10.00| 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00
-20.00	 5.00	 6.00	-12.00	 9.00	 18.00	-15.00	 14.00	-1.00	 9.00| 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00
 8.00	 10.00	-3.00	-16.00	-3.00	-13.00	 12.00	 11.00	-2.00	-17.00| 0.00	 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00
 19.00	-10.00	-12.00	-8.00	 15.00	-4.00	 13.00	-6.00	-20.00	-8.00| 0.00	 0.00	 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00
 7.00	 17.00	-11.00	-12.00	 7.00	 17.00	 17.00	-13.00	 4.00	-3.00| 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00
-12.00	 5.00	-17.00	 16.00	 10.00	-11.00	 10.00	 16.00	 7.00	 5.00| 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00

array([[-6.94423870e-02,  1.68866494e-02,  2.78743942e-02,
         1.01009290e-02, -1.87162259e-02,  1.27779603e-02,
         2.44518402e-02, -4.67584668e-02, -1.16132078e-03,
        -2.68944424e-02],
       [ 2.14775385e-02,  3.36216260e-02,  3.38987722e-02,
         2.64059491e-02,  4.04243437e-02, -5.34416729e-03,
         1.54245929e-02, -2.66578538e-02,  5.80728277e-02,
        -3.87538573e-04],
       [-2.26343278e-03,  2.85138415e-03, -3.13524049e-03,
         1.33238334e-02,  4.70766566e-03, -2.43706119e-02,
         4.53863655e-03, -8.45406279e-03,  1.78845943e-02,
        -2.46725119e-02],
       [ 2.54334075e-02, -1.79179099e-02,  3.27404090e-02,
        -7.65403362e-03,  2.22791357e-03, -1.34137090e-02,
         3.38982626e-03,  1.93938434e-02,  4.19331867e-02,
        -1.52427814e-02],
       [ 2.26291585e-02, -2.07757447e-03,  2.91590362e-02,
         1.81069698e-03,  2.29759554e-02, -6.62710066e-03,
         9.74076065e-04,  1.19601123e-02,  1.03213306e-02,
        -4.

Comprobamos que en realidad sea la inversa, el resultado debe ser la matriz identidad. Hacemos la comparativa con la identidad que sea lo suficientemente cercana.

In [21]:
np.matmul(A,A_inv)

array([[ 1.00000000e+00,  5.27355937e-16, -2.56739074e-16,
        -6.10622664e-16, -4.02455846e-16,  1.24900090e-16,
         1.66533454e-16, -7.63278329e-17, -1.52655666e-16,
        -1.56125113e-16],
       [-2.59514632e-15,  1.00000000e+00,  5.75928194e-16,
         8.32667268e-16, -6.24500451e-16,  2.91433544e-16,
        -1.11022302e-16, -4.09394740e-16,  1.24900090e-16,
        -2.94902991e-16],
       [-2.91433544e-15,  8.32667268e-16,  1.00000000e+00,
         4.44089210e-16, -6.38378239e-16,  5.82867088e-16,
        -1.11022302e-16, -4.57966998e-16, -8.32667268e-17,
        -2.98372438e-16],
       [-4.39925874e-15,  2.13717932e-15, -2.98372438e-16,
         1.00000000e+00, -1.48492330e-15,  4.85722573e-16,
         5.55111512e-16, -1.08940634e-15, -4.02455846e-16,
        -3.15719673e-16],
       [-2.37310172e-15, -2.24820162e-15,  1.02001740e-15,
         1.38777878e-15,  1.00000000e+00,  1.24900090e-16,
        -2.77555756e-17, -5.20417043e-16, -4.16333634e-17,
        -4.

In [22]:
np.allclose(
      np.matmul(A,A_inv),
      np.eye(n)
      )

True

También existe la función inv que obtiene el mismo resultado, incluso podemos comprobar que sea en realidad la inversa.

In [23]:
A_inv_2 = np.linalg.inv(A)
A_inv_2

array([[-6.94423870e-02,  1.68866494e-02,  2.78743942e-02,
         1.01009290e-02, -1.87162259e-02,  1.27779603e-02,
         2.44518402e-02, -4.67584668e-02, -1.16132078e-03,
        -2.68944424e-02],
       [ 2.14775385e-02,  3.36216260e-02,  3.38987722e-02,
         2.64059491e-02,  4.04243437e-02, -5.34416729e-03,
         1.54245929e-02, -2.66578538e-02,  5.80728277e-02,
        -3.87538573e-04],
       [-2.26343278e-03,  2.85138415e-03, -3.13524049e-03,
         1.33238334e-02,  4.70766566e-03, -2.43706119e-02,
         4.53863655e-03, -8.45406279e-03,  1.78845943e-02,
        -2.46725119e-02],
       [ 2.54334075e-02, -1.79179099e-02,  3.27404090e-02,
        -7.65403362e-03,  2.22791357e-03, -1.34137090e-02,
         3.38982626e-03,  1.93938434e-02,  4.19331867e-02,
        -1.52427814e-02],
       [ 2.26291585e-02, -2.07757447e-03,  2.91590362e-02,
         1.81069698e-03,  2.29759554e-02, -6.62710066e-03,
         9.74076065e-04,  1.19601123e-02,  1.03213306e-02,
        -4.

In [24]:
np.allclose(
      np.matmul(A,A_inv_2),
      np.eye(n)
      )

True

**Ejercicio**: Que sucede cuando la matriz no es invertible? Genera un caso.

In [36]:

zero_a = A.copy()
#zero_a
zero_a[4] = 0
zero_a

array([[ -8,  -1,   2,  -8,  12,  18,  -8, -18,  -2,   7],
       [ -9,   8, -11,  12,  11, -11,   2,  -3,  11,  15],
       [-12,   8, -19,  11,   2,   8, -18,   8,  13,  10],
       [-20,   5,   6, -12,   9,  18, -15,  14,  -1,   9],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 19, -10, -12,  -8,  15,  -4,  13,  -6, -20,  -8],
       [  7,  17, -11, -12,   7,  17,  17, -13,   4,  -3],
       [-12,   5, -17,  16,  10, -11,  10,  16,   7,   5],
       [ 13,  -4,  10,  16, -10, -14,  12,   0, -11,  -7],
       [-12,  13, -14,   3, -20,   4,  -7,   8,   9,   2]])

In [37]:
np.linalg.det(zero_a)

0.0

In [39]:
zero_a_inv = inversa_gauss_jordan(zero_a)

Columna 0
Fila 0
 1.00	 0.12	-0.25	 1.00	-1.50	-2.25	 1.00	 2.25	 0.25	-0.88|-0.12	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00	-0.00
-9.00	 8.00	-11.00	 12.00	 11.00	-11.00	 2.00	-3.00	 11.00	 15.00| 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00
-12.00	 8.00	-19.00	 11.00	 2.00	 8.00	-18.00	 8.00	 13.00	 10.00| 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00
-20.00	 5.00	 6.00	-12.00	 9.00	 18.00	-15.00	 14.00	-1.00	 9.00| 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00
 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00| 0.00	 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00	 0.00
 19.00	-10.00	-12.00	-8.00	 15.00	-4.00	 13.00	-6.00	-20.00	-8.00| 0.00	 0.00	 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00	 0.00
 7.00	 17.00	-11.00	-12.00	 7.00	 17.00	 17.00	-13.00	 4.00	-3.00| 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 1.00	 0.00	 0.00	 0.00
-12.00	 5.00	-17.00	 16.00	 10.00	-11.00	 10.00	 16.00	 7.00	 5.00| 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 0.00	 1.00

/tmp/ipykernel_7454/1383108377.py:23: RuntimeWarning: divide by zero encountered in scalar divide
  factor = - matriz[fila,columna] / matriz[columna,columna]
/tmp/ipykernel_7454/1383108377.py:26: RuntimeWarning: invalid value encountered in multiply
  matriz[fila,:] = matriz[columna,:] * factor + matriz[fila,:]
/tmp/ipykernel_7454/1383108377.py:27: RuntimeWarning: invalid value encountered in multiply
  inversa[fila,:] = inversa[columna,:] * factor + inversa[fila,:]
/tmp/ipykernel_7454/1383108377.py:18: RuntimeWarning: divide by zero encountered in scalar divide
  factor = 1/matriz[fila,columna]
/tmp/ipykernel_7454/1383108377.py:19: RuntimeWarning: invalid value encountered in multiply
  matriz[fila,:] = matriz[fila,:] * factor
/tmp/ipykernel_7454/1383108377.py:20: RuntimeWarning: invalid value encountered in multiply
  inversa[fila,:] = inversa[fila,:] * factor


In [45]:
zero_a_inv

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [40]:
np.matmul(zero_a, zero_a_inv)

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [41]:
np.allclose(
      np.matmul(zero_a,zero_a_inv),
      np.eye(n)
      )

False

In [44]:
zero_a_inv2 = np.linalg.inv(zero_a)

LinAlgError: Singular matrix

## Ejercicio medir tiempo con matrices grandes


In [64]:
import datetime
now = datetime.datetime.now()
now

datetime.datetime(2023, 6, 3, 12, 21, 31, 679419)

In [73]:
n = 1000
lil_boy = np.random.randint(20, size=(n,n))
lil_boy

array([[17,  9, 14, ...,  6,  4, 17],
       [14,  3,  0, ...,  7,  7,  1],
       [ 9, 11, 11, ..., 10, 10,  2],
       ...,
       [14,  8,  4, ...,  0, 18,  4],
       [ 3, 10,  7, ...,  4,  0,  6],
       [10,  7,  0, ...,  0,  5,  1]])

In [ ]:
sta = datetime.datetime.now()
lil_boy_inv = inversa_gauss_jordan(lil_boy)
fin = datetime.datetime.now()
print(f'Completed in: {fin - sta}')
print(np.matmul(lil_boy, lil_boy_inv))

In [72]:
sta = datetime.datetime.now()
fin = datetime.datetime.now()
print(f'Completed in: {fin - sta}')
print(np.matmul(lil_boy, lil_boy_inv2))

Completed in: 0:00:00.259637
[[ 1.00000000e+00 -6.02295991e-15  1.37667655e-14 ...  1.05471187e-15
  -2.77555756e-16 -1.42663659e-14]
 [ 1.11022302e-15  1.00000000e+00 -5.55111512e-16 ... -4.71844785e-16
  -2.77555756e-17 -1.11022302e-16]
 [-9.27036226e-15  1.09634524e-15  1.00000000e+00 ...  3.87190280e-14
  -2.67841305e-15 -6.57807142e-15]
 ...
 [-2.83661983e-14  3.10862447e-15 -1.19348975e-14 ...  1.00000000e+00
   1.80411242e-16 -1.36002321e-14]
 [-7.10542736e-15  1.27675648e-14 -1.26010313e-14 ...  7.63278329e-15
   1.00000000e+00 -1.08246745e-14]
 [-1.45994328e-14 -1.13242749e-14  2.49800181e-15 ...  1.22124533e-15
  -1.55431223e-15  1.00000000e+00]]
