# Método de Gauss

En este cuaderno veremos algunos ejemplos de como se aplica eliminacion gaussiana

Comenzamos importando numpy


In [1]:
import numpy as np

Creamos una funcion que ejecutara el metodo de Gauss para resolver el sistema de ecuaciones 

In [2]:
def metodo_gauss(matriz_coeficientes,vector_independiente):
  print("Metodo de gauss")
  matriz = matriz_coeficientes.astype(float)
  vector = vector_independiente.astype(float)
  n_filas, n_columnas= matriz.shape
  for columna in range(n_columnas-1):
    print(f"Columna {columna}")
    for fila in range(columna+1,n_filas):
      print(f"Fila {fila}")
      factor = - matriz[fila,columna] / matriz[columna,columna]
      print(f"factor de {factor} ")
      print(f"R{fila} --> {factor}*R{columna} + R{fila}") 
      matriz[fila,:] = matriz[columna,:] * factor + matriz[fila,:]
      vector[fila,:] = vector[columna,:] * factor + vector[fila,:]
      imprimir_sistema(matriz,vector)
  incognita = np.zeros_like (vector)
  for columna in range(n_columnas-1,-1,-1):
    #print(columna)
    valor = (vector[columna,0] - np.matmul( matriz[columna,:],incognita)) / matriz[columna,columna]
    print(f"Valor de x_{columna} = {valor}")
    incognita[columna,0] = valor
    #print(incognita)
  print(f"Valor de X \n{incognita}")

def imprimir_sistema(matriz_coeficientes,vector_independiente):
  n_filas, n_columnas= matriz_coeficientes.shape
  for fila in range(n_filas):
    columnas = [f"{x: 8.2f}" for x in matriz_coeficientes[fila,:].tolist()[0]]
    print(f"{''.join(columnas)} | {vector_independiente[fila,0]: 8.2f}")


Definimos nuestro sistema de ecuaciones y llamamos a la funcion para resolver el sistema

In [3]:
matriz_coeficientes = np.matrix(
    "1 1 0; 0 1 -1; 1 0 -1"
    )

vector_independiente = np.matrix("13; 5; 2")

print(f"Matriz de coeficientes: \n{matriz_coeficientes}")
print(f"Vector independiente: \n{vector_independiente}")


metodo_gauss(matriz_coeficientes,vector_independiente)

Matriz de coeficientes: 
[[ 1  1  0]
 [ 0  1 -1]
 [ 1  0 -1]]
Vector independiente: 
[[13]
 [ 5]
 [ 2]]
Metodo de gauss
Columna 0
Fila 1
factor de -0.0 
R1 --> -0.0*R0 + R1
    1.00    1.00    0.00 |    13.00
    0.00    1.00   -1.00 |     5.00
    1.00    0.00   -1.00 |     2.00
Fila 2
factor de -1.0 
R2 --> -1.0*R0 + R2
    1.00    1.00    0.00 |    13.00
    0.00    1.00   -1.00 |     5.00
    0.00   -1.00   -1.00 |   -11.00
Columna 1
Fila 2
factor de 1.0 
R2 --> 1.0*R1 + R2
    1.00    1.00    0.00 |    13.00
    0.00    1.00   -1.00 |     5.00
    0.00    0.00   -2.00 |    -6.00
Valor de x_2 = [[3.]]
Valor de x_1 = [[8.]]
Valor de x_0 = [[5.]]
Valor de X 
[[5.]
 [8.]
 [3.]]


In [4]:
matriz_coeficientes = np.matrix(
    "1 2 0; 0 1 -3; 3 0 -1"
    )

vector_independiente = np.matrix("5; 5; 4")

print(f"Matriz de coeficientes: \n{matriz_coeficientes}")
print(f"Vector independiente: \n{vector_independiente}")


metodo_gauss(matriz_coeficientes,vector_independiente)

Matriz de coeficientes: 
[[ 1  2  0]
 [ 0  1 -3]
 [ 3  0 -1]]
Vector independiente: 
[[5]
 [5]
 [4]]
Metodo de gauss
Columna 0
Fila 1
factor de -0.0 
R1 --> -0.0*R0 + R1
    1.00    2.00    0.00 |     5.00
    0.00    1.00   -3.00 |     5.00
    3.00    0.00   -1.00 |     4.00
Fila 2
factor de -3.0 
R2 --> -3.0*R0 + R2
    1.00    2.00    0.00 |     5.00
    0.00    1.00   -3.00 |     5.00
    0.00   -6.00   -1.00 |   -11.00
Columna 1
Fila 2
factor de 6.0 
R2 --> 6.0*R1 + R2
    1.00    2.00    0.00 |     5.00
    0.00    1.00   -3.00 |     5.00
    0.00    0.00  -19.00 |    19.00
Valor de x_2 = [[-1.]]
Valor de x_1 = [[2.]]
Valor de x_0 = [[1.]]
Valor de X 
[[ 1.]
 [ 2.]
 [-1.]]


## Método de Gauss jordan

In [5]:
def metodo_gauss_jordan(matriz_coeficientes,vector_independiente):
  print("Metodo de Gauss-Jordan")
  matriz = matriz_coeficientes.astype(float)
  vector = vector_independiente.astype(float)
  n_filas, n_columnas= matriz.shape
  for columna in range(n_columnas):
    print(f"Columna {columna}")
    for fila in range(n_filas):
      if not fila == columna:
        print(f"Fila {fila}")
        factor = - matriz[fila,columna] / matriz[columna,columna]
        print(f"factor de {factor} ")
        print(f"R{fila} --> {factor}*R{columna} + R{fila}") 
        matriz[fila,:] = matriz[columna,:] * factor + matriz[fila,:]
        vector[fila,:] = vector[columna,:] * factor + vector[fila,:]
        imprimir_sistema(matriz,vector)
  incognita = np.zeros(vector.shape)
  for columna in range(n_columnas-1,-1,-1):
    #print(columna)
    valor = vector[columna,0] / matriz[columna,columna]
    print(f"Valor de x_{columna} = {valor}")
    incognita[columna,0] = valor
    #print(incognita)
  print(f"Valor de X \n{incognita}")

In [6]:
matriz_coeficientes = np.matrix(
    "1 1 0; 0 1 -1; 1 0 -1"
    )

vector_independiente = np.matrix("13; 5; 2")

print(f"Matriz de coeficientes: \n{matriz_coeficientes}")
print(f"Vector independiente: \n{vector_independiente}")


metodo_gauss_jordan(matriz_coeficientes,vector_independiente)

Matriz de coeficientes: 
[[ 1  1  0]
 [ 0  1 -1]
 [ 1  0 -1]]
Vector independiente: 
[[13]
 [ 5]
 [ 2]]
Metodo de Gauss-Jordan
Columna 0
Fila 1
factor de -0.0 
R1 --> -0.0*R0 + R1
    1.00    1.00    0.00 |    13.00
    0.00    1.00   -1.00 |     5.00
    1.00    0.00   -1.00 |     2.00
Fila 2
factor de -1.0 
R2 --> -1.0*R0 + R2
    1.00    1.00    0.00 |    13.00
    0.00    1.00   -1.00 |     5.00
    0.00   -1.00   -1.00 |   -11.00
Columna 1
Fila 0
factor de -1.0 
R0 --> -1.0*R1 + R0
    1.00    0.00    1.00 |     8.00
    0.00    1.00   -1.00 |     5.00
    0.00   -1.00   -1.00 |   -11.00
Fila 2
factor de 1.0 
R2 --> 1.0*R1 + R2
    1.00    0.00    1.00 |     8.00
    0.00    1.00   -1.00 |     5.00
    0.00    0.00   -2.00 |    -6.00
Columna 2
Fila 0
factor de 0.5 
R0 --> 0.5*R2 + R0
    1.00    0.00    0.00 |     5.00
    0.00    1.00   -1.00 |     5.00
    0.00    0.00   -2.00 |    -6.00
Fila 1
factor de -0.5 
R1 --> -0.5*R2 + R1
    1.00    0.00    0.00 |     5.00
    0.00    1

In [7]:
matriz_coeficientes = np.matrix(
    "-1 3 0; 3 4 -4; -20 -12 5"
    )

vector_independiente = np.matrix("-72; -4; -50")

print(f"Matriz de coeficientes: \n{matriz_coeficientes}")
print(f"Vector independiente: \n{vector_independiente}")


metodo_gauss_jordan(matriz_coeficientes,vector_independiente)

Matriz de coeficientes: 
[[ -1   3   0]
 [  3   4  -4]
 [-20 -12   5]]
Vector independiente: 
[[-72]
 [ -4]
 [-50]]
Metodo de Gauss-Jordan
Columna 0
Fila 1
factor de 3.0 
R1 --> 3.0*R0 + R1
   -1.00    3.00    0.00 |   -72.00
    0.00   13.00   -4.00 |  -220.00
  -20.00  -12.00    5.00 |   -50.00
Fila 2
factor de -20.0 
R2 --> -20.0*R0 + R2
   -1.00    3.00    0.00 |   -72.00
    0.00   13.00   -4.00 |  -220.00
    0.00  -72.00    5.00 |  1390.00
Columna 1
Fila 0
factor de -0.23076923076923078 
R0 --> -0.23076923076923078*R1 + R0
   -1.00    0.00    0.92 |   -21.23
    0.00   13.00   -4.00 |  -220.00
    0.00  -72.00    5.00 |  1390.00
Fila 2
factor de 5.538461538461538 
R2 --> 5.538461538461538*R1 + R2
   -1.00    0.00    0.92 |   -21.23
    0.00   13.00   -4.00 |  -220.00
    0.00    0.00  -17.15 |   171.54
Columna 2
Fila 0
factor de 0.053811659192825115 
R0 --> 0.053811659192825115*R2 + R0
   -1.00    0.00    0.00 |   -12.00
    0.00   13.00   -4.00 |  -220.00
    0.00    0.00  -17.

## Funcion de python

In [8]:
np.linalg.solve(matriz_coeficientes, vector_independiente)

matrix([[ 12.],
        [-20.],
        [-10.]])