# Independencia lineal.

En este cuaderno veremos algunos ejemplos de independencia lineal, cómo calcularlos, y conceptos relacionados.

Comenzamos importando la librería numpy. Que nos ayudará a trabajar con matrices y vectores.


In [1]:
import numpy as np
from numpy.linalg import LinAlgError

Definimos una función que nos ayudará A encontrar si un vector es linealmente independiente a un conjunto dado. 

Internamente, usa la implementación de resolución de sistemas de ecuaciones de numpy. Sin embargo, este implementación sólo admite matrices cuadradas. Por lo que si falla. Se utilizará mínimos cuadrados.

In [2]:
def independencia_lineal(vector, conjunto):
  A = np.array(conjunto).transpose()
  ind = np.array(vector).transpose()
  try:
    x = np.linalg.solve(A,ind)
  except LinAlgError:
    print("Matriz no cuadrada, intentando con minimos cuadrados ")
    x,res,rank,s = np.linalg.lstsq(A,ind,rcond=None)
    #print(f"Rango {rank}")
  return x

Se crean 3 vectores aleatorios. Los cual es se utilizarán para probar la Independencia lineal.

In [3]:
a = np.random.randint(10, size=4)
b = np.random.randint(10, size=4)
c = np.random.randint(10, size=4)
print(a,b,c)

[4 9 8 1] [4 0 2 0] [4 7 7 5]


Se ejecuta la función de independencia lineal. Para probar la Independencia del vector C contra el Grupo de A y B. La respuesta se usa para calcular la combinación lineal y se compara con el vector.

Vemos que las diferencias son notables. Por lo tanto son linealmente independientes

In [5]:
x = independencia_lineal(c, [a,b])
print(x)
print("a")
(x[0]*a + x[1]*b ) - c

Matriz no cuadrada, intentando con minimos cuadrados 
[0.83032491 0.17148014]
a


array([ 0.00722022,  0.47292419, -0.01444043, -4.16967509])

Ahora creamos un elemento linealmente depenediente al definirlo como una combinación lineal.

In [6]:
a = np.random.randint(10, size=4)
b = np.random.randint(10, size=4)
c = a+2*b
print(a)
print(b)
print(c)

[8 7 4 3]
[0 7 1 3]
[ 8 21  6  9]


Calculamos los factores de su combinación lineal(que ya conocemos) y coparamos la combinación lineal con el vector. Vemos que la diferencia esta a nivel de maquina por lo que si es linealmente dependiente

In [7]:
x = independencia_lineal(c, [a,b])
print(x)

(x[0]*a + x[1]*b ) - c

Matriz no cuadrada, intentando con minimos cuadrados 
[1. 2.]


array([1.06581410e-14, 1.42108547e-14, 6.21724894e-15, 7.10542736e-15])

## Conjuntos linealmente independientes
Definimos una función que no ayuda a saber si un conjunto es linealmente independiente. Tomando un elmento y comparándolo contra los demás .


In [8]:
def concunto_li(conjunto):
  c = conjunto[1:]
  vec =  conjunto[0]
  return independencia_lineal(vec, c)

Utilzando el ejemplo anterior, vemos que la diferencia es 0 por lo que este conjunto es linealmente dependiente

In [9]:
x = concunto_li([a,b,c])
print(x)

(x[0]*b + x[1]*c ) - a

Matriz no cuadrada, intentando con minimos cuadrados 
[-2.  1.]


array([-6.21724894e-15, -1.24344979e-14, -3.55271368e-15, -5.32907052e-15])

# Numero de soluciones de un sistema de ecuaciones 
Definimos un sistema de ecuaciones lineales en el cual la ultima fila de A es una combinación lineal de la primera. Sin embargo B es aleatorio independiente.


In [10]:
A = np.random.randint(20, size=(5,5)) - 10
x = np.random.randint(20, size=(5,1)) - 10
b = np.matmul(A,x)
A[-1] = A[0]*2
B = np.concatenate([A,b],1)
print(A)
print(x)
print(b)
print(B)

[[ -7 -10  -7  -9   0]
 [ -2   4  -7  -8  -4]
 [  2   4 -10   3  -7]
 [ -7  -5  -5   3  -2]
 [-14 -20 -14 -18   0]]
[[ 2]
 [ 4]
 [-9]
 [-7]
 [ 0]]
[[  72]
 [ 131]
 [  89]
 [ -10]
 [-112]]
[[  -7  -10   -7   -9    0   72]
 [  -2    4   -7   -8   -4  131]
 [   2    4  -10    3   -7   89]
 [  -7   -5   -5    3   -2  -10]
 [ -14  -20  -14  -18    0 -112]]


Calculamos el rango de la matriz A y de la matriz compuesta B, vemos que los rangos son distintos. Por lo queesperamos que el sistema no se pueda resolver.

In [11]:
print(f"Rango A: {np.linalg.matrix_rank(A)}")

print(f"Rango B: {np.linalg.matrix_rank(B)}")

np.linalg.solve(A,b)

Rango A: 4
Rango B: 5


LinAlgError: Singular matrix

Ahora definimos un sistema de ecuaciones completamente aletatrorio y bien definido. 

In [12]:
A = np.random.randint(20, size=(5,5)) - 10
x = np.random.randint(20, size=(5,1)) - 10
b = np.matmul(A,x)
B = np.concatenate([A,b],1)
print(A)
print(x)
print(b)
print(B)

[[ -9   9  -3  -3   3]
 [ -7  -6  -2  -1   7]
 [ -2 -10  -7  -1   1]
 [  7   0  -3  -5   1]
 [  3   0   1  -6  -8]]
[[-6]
 [ 7]
 [-5]
 [ 9]
 [-5]]
[[ 90]
 [-34]
 [-37]
 [-77]
 [-37]]
[[ -9   9  -3  -3   3  90]
 [ -7  -6  -2  -1   7 -34]
 [ -2 -10  -7  -1   1 -37]
 [  7   0  -3  -5   1 -77]
 [  3   0   1  -6  -8 -37]]


En este caso vemos que coincide el rango de A el rango de B y el numero de columnas po lo que la solución es única.

In [13]:
print(f"Rango A: {np.linalg.matrix_rank(A)}")
print(f"Rango b: {np.linalg.matrix_rank(B)}")
A.shape[1]

Rango A: 5
Rango b: 5


5

Corroboramos esto al resolver el sistema y comparando el resultado.

In [14]:
x2 = np.linalg.solve(A,b)
print(x2)

x2-x

[[-6.]
 [ 7.]
 [-5.]
 [ 9.]
 [-5.]]


array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 2.66453526e-15],
       [-1.77635684e-15],
       [ 0.00000000e+00]])

Ahora vemos un ejemplo de un sistema de ecuaciones donde el rango de A y de B coinciden, pero son menores al numero de columnas. Por lo tanto el sistema tendrá infinitas soluciones

In [15]:
A = np.random.randint(20, size=(5,5)) - 10
x = np.random.randint(20, size=(5,1)) - 10
A[-1] = A[0]*2
b = np.matmul(A,x)
B = np.concatenate([A,b],1)
print(A)
print(x)
print(b)
print(B)

[[  1  -1   3   5   8]
 [ -8   4  -9  -7 -10]
 [ -3   7  -2   2   2]
 [ -7   0  -8  -1  -9]
 [  2  -2   6  10  16]]
[[-9]
 [-7]
 [ 4]
 [ 6]
 [-2]]
[[ 24]
 [-14]
 [-22]
 [ 43]
 [ 48]]
[[  1  -1   3   5   8  24]
 [ -8   4  -9  -7 -10 -14]
 [ -3   7  -2   2   2 -22]
 [ -7   0  -8  -1  -9  43]
 [  2  -2   6  10  16  48]]


In [16]:
print(f"Rango A: {np.linalg.matrix_rank(A)}")
print(f"Rango b: {np.linalg.matrix_rank(B)}")
A.shape[1]

Rango A: 4
Rango b: 4


5

Como tiene infinitas soluciones el método da un error, lo que hacemos es calcular mediante mínimos cuadrados la respuesta .



In [17]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

Si comparamos con la respuesta original, vemos que son significativamente diferentes.
Sin abmargo al usarla en el sistema de ecauciones, vemos que es una solución correcta 

In [18]:
x2,res,rank,s = np.linalg.lstsq(A,b,rcond=None)
print(x2)

print(x2 -x)

np.matmul(A,x2) - b

[[-3.74993402]
 [-7.21575614]
 [-2.83227765]
 [ 5.78424386]
 [ 0.01372394]]
[[ 5.25006598]
 [-0.21575614]
 [-6.83227765]
 [-0.21575614]
 [ 2.01372394]]


array([[ 7.10542736e-15],
       [-3.55271368e-14],
       [ 2.13162821e-14],
       [-1.42108547e-14],
       [ 1.42108547e-14]])

# Sistemas mal condicionados
Ahora reproducciones el caso en un sistema de ecuaciones donde una fila es casi linealmente dependiente de otra. 


In [19]:
A = (np.random.randint(20, size=(5,5)) - 10).astype(float)
x = (np.random.randint(20, size=(5,1)) - 10).astype(float)
b = np.matmul(A,x)
A[-1] = A[0]*2
A[-1][0] += 0.000000001
B = np.concatenate([A,b],1)
print(A)
print(x)
print(b)
print(B)

[[  5.  -6.   8.  -1.  -7.]
 [-10. -10.   6.   6.   7.]
 [  2.  -1.  -8.   3.  -7.]
 [  0.   8.  -2.   5.  -7.]
 [ 10. -12.  16.  -2. -14.]]
[[ 2.]
 [-1.]
 [ 7.]
 [-9.]
 [ 8.]]
[[  25.]
 [  34.]
 [-134.]
 [-123.]
 [  41.]]
[[   5.   -6.    8.   -1.   -7.   25.]
 [ -10.  -10.    6.    6.    7.   34.]
 [   2.   -1.   -8.    3.   -7. -134.]
 [   0.    8.   -2.    5.   -7. -123.]
 [  10.  -12.   16.   -2.  -14.   41.]]


Ya que en el sentido estricto, son linealmente independientes, los rangos se mantendrán completos por lo que este sistema tendrá una única solución.

In [20]:
print(f"Rango A: {np.linalg.matrix_rank(A)}")
print(f"Rango b: {np.linalg.matrix_rank(B)}")
A.shape[1]

Rango A: 5
Rango b: 5


5

Calculamos la solución, y la comparamos con la solución original. Vemos que las diferencias notables.

Al resolver el sistema de ecuaciones vemos que si tiende a 0 pero esta lejos de la precisión de computadora

In [21]:
x2 = np.linalg.solve(A,b)
print(x2)

print(x-x2)

np.matmul(A,x2) - b

[[-9.00000364e+09]
 [ 8.45070665e+06]
 [-3.25352237e+08]
 [-8.06197510e+09]
 [-5.65593789e+09]]
[[ 9.00000364e+09]
 [-8.45070765e+06]
 [ 3.25352244e+08]
 [ 8.06197509e+09]
 [ 5.65593790e+09]]


array([[ 1.62124634e-05],
       [-2.38418579e-05],
       [ 8.58306885e-06],
       [ 9.53674316e-07],
       [ 3.24249268e-05]])

In [22]:
def es_ortogonal(v1,v2):
  return np.matmul(v1,v2.transpose()) == 0

# Vectores ortogonales
Definimos una función que nos ayuda a saber si dos vectores son ortogonales. 
Hacemos la prueba con dos vectores canónicos.


In [23]:
a = np.array([1,0])
b = np.array([0,1])
es_ortogonal(a,b)

True

Si modificamos los vectores vemos que ya no son ortogonales

In [24]:
a = np.array([1,0])
b = np.array([1,1])
es_ortogonal(a,b)

False