# Determinantes

En este cuaderno revisaremos como calcular el determinante de una matriz y revisaremos sus principales propiedades.

Numpy ofrece una función para calcular estos determinantes de manera sencilla, la cual importaremos.


In [1]:
import numpy as np
from numpy.linalg import det


## Determinante de matrices 2x2 
Comenzamos revisando que la formula presentada si coincide con el determinante


In [4]:
A = np.random.randint(10, size=(2,2)) 
A

array([[9, 2],
       [8, 4]])

In [6]:
print(det(A))
print(A[0,0]*A[1,1]-A[0,1]*A[1,0])

20.000000000000007
20


# Determinante de renglones nulos 
Si una matriz tiene un renglón de ceros entonces su determinante será 0


In [7]:
A = np.random.randint(10, size=(4,4)) 
A[0] = np.zeros_like(A[0])
A

array([[0, 0, 0, 0],
       [6, 8, 0, 9],
       [2, 2, 3, 6],
       [3, 1, 3, 0]])

In [8]:
det(A)

0.0

# Intercambio de filas
Si se intercambian dos filas el signo de determinante se invierte


In [9]:
A = np.random.randint(10, size=(4,4)) 
B = A.copy()
fila = B[0].copy()
B[0] = B[1]
B[1] = fila
print(A)
print(B)

[[9 2 1 1]
 [3 2 4 4]
 [7 8 1 1]
 [9 7 2 6]]
[[3 2 4 4]
 [9 2 1 1]
 [7 8 1 1]
 [9 7 2 6]]


In [10]:
print(det(A))
print(det(B))


-840.0000000000007
840.0000000000007


# Multiplicación escalar

In [11]:
A = np.random.randint(10, size=(4,4))
B = A.copy()
B[0] = B[0]*5
print(A)
print(B)

[[5 6 1 7]
 [2 6 4 2]
 [9 0 7 2]
 [7 0 3 4]]
[[25 30  5 35]
 [ 2  6  4  2]
 [ 9  0  7  2]
 [ 7  0  3  4]]


In [12]:
print(det(A))
print(det(A)*5)
print(det(B))

132.0000000000003
660.0000000000016
659.9999999999987


# Determinantes con el método de gauss
Si se suma a una fila o a una columna de una matriz un múltiplo de otra fila o columna, el valor del determinante no cambia.


In [13]:
A = np.random.randint(10, size=(4,4))
B = A.copy()
B[0] = B[0] + B[1]*5
print(A)
print(B)

[[8 5 6 8]
 [6 2 6 6]
 [2 6 7 7]
 [0 6 3 3]]
[[38 15 36 38]
 [ 6  2  6  6]
 [ 2  6  7  7]
 [ 0  6  3  3]]


In [14]:
print(det(A))
print(det(B))

167.99999999999997
167.99999999999997


# Determinante de una matrix triangular
El determinante es igual al producto de los elementos de la diagonal principal.


In [20]:
A = np.triu(np.random.randint(10, size=(4,4)))
print(A)


[[1 4 1 8]
 [0 6 2 5]
 [0 0 3 8]
 [0 0 0 8]]


In [21]:
print(det(A))
print(np.prod( np.diag(A)))

143.9999999999999
144


# Matrices mal condicionadas
Otra manera de encontrar matrices mal condicionadas es si su determinante es muy pequeño pero distinto de 0 
Matrices casi linealmente dependiente


In [37]:
A = (np.random.randint(20, size=(5,5)) - 10).astype(float)
#A[-1] = A[0]*2
#A[-1][0] += 0.000000001
print(A)

[[  8.  -2.   7.   2.  -6.]
 [  8.   7.  -7.   1.   9.]
 [  5.  -9.   7.  -1. -10.]
 [  4.  -1.   7.  -3.   6.]
 [ -9.  -5.  -7.   4.  -4.]]


In [38]:
det(A)

48083.000000000044

In [39]:
A[-1][0] += 0.000000001
det(A)

48082.99999948201