## Vectores y Valores Propios

En este cuaderno se verán algunos ejemplos de cómo obtener y calcular valores propios.

In [1]:
import numpy as np

Comenzaremos generando una matriz aleatoria hola cuadrada. 

In [2]:
A = np.random.randint(10, size=(4,4)) 
A

array([[1, 1, 8, 7],
       [3, 3, 1, 3],
       [4, 0, 4, 8],
       [5, 5, 3, 6]])

El primer paso es calcular el polinomio característico de la matriz. 

In [3]:
polinomio_caracteristico = np.poly(A)
print("\nEcuación característica:")
print(np.poly1d(polinomio_caracteristico))


Ecuación característica:
   4      3      2
1 x - 14 x - 42 x + 40 x + 4


Calculamos las raíces del polinomio obtenido, estos serán los valores propios dados.

In [4]:
raices = np.roots(polinomio_caracteristico)
raices

array([16.40997364, -3.16133146,  0.84284008, -0.09148226])

Si tomamos, por ejemplo, el primer valor propio e intentamos resolver el sistema de ecuaciones, veremos que la solución es el vector nulo. 

Esta solución es correcta, veremos que el sistema tiene un número infinito de soluciones, por lo cual la solución deberá ser calculada de manera manual.

In [5]:
raiz = raices[0]
sistema = A-(np.eye(4)*raiz)
sistema

array([[-15.40997364,   1.        ,   8.        ,   7.        ],
       [  3.        , -13.40997364,   1.        ,   3.        ],
       [  4.        ,   0.        , -12.40997364,   8.        ],
       [  5.        ,   5.        ,   3.        , -10.40997364]])

In [6]:
np.linalg.solve( sistema, np.zeros((4,1)))

array([[-0.],
       [-0.],
       [-0.],
       [-0.]])

Afortunadamente, en numpy ofrece métodos para calcular valores y vectores propios de manera directa, los cuales se muestran a continuación.



In [7]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Valores propios:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

print("\nVectores propios:")
for eigenvector in eigenvectors.T:
    print(eigenvector)

Valores propios:
16.409973643477727
-3.1613314622797497
0.8428400807481896
-0.09148226194616565

Vectores propios:
[-0.55477694 -0.29010362 -0.5409015  -0.5616832 ]
[-0.90095434  0.27064738  0.18755076  0.28258802]
[-0.61870394  0.39019758 -0.46939053  0.49459459]
[-0.671966    0.25286763 -0.42337773  0.55251331]


Podemos comprobar que estos vectores propios son correctos al multiplicar la matriz A por cada uno de los vectores propios, y esto debe ser igual al vector propio multiplicado por el valor propio.

In [8]:
for eigenvalue, eigenvector in zip(eigenvalues, eigenvectors.T):
  print(f"{np.matmul(A,eigenvector)} == {eigenvalue*eigenvector}")

[-9.1038749  -4.76059275 -8.8761793  -9.21720644] == [-9.1038749  -4.76059275 -8.8761793  -9.21720644]
[ 2.8482153  -0.85560606 -0.59291013 -0.8933544 ] == [ 2.8482153  -0.85560606 -0.59291013 -0.8933544 ]
[-0.52146848  0.32887416 -0.39562115  0.41686415] == [-0.52146848  0.32887416 -0.39562115  0.41686415]
[ 0.06147297 -0.0231329   0.03873155 -0.05054517] == [ 0.06147297 -0.0231329   0.03873155 -0.05054517]


## Método de la potencia 
definimos un número de iteraciones y un vector propio inicial, 
El cuál iremos multiplicado por potencias de la matriz A hasta que encontremos convergencia en el vector valor propio dominante.


In [14]:
iteraciones = 50
x = np.array([1,0,0,0])
x

array([1, 0, 0, 0])

In [15]:
for i in range(iteraciones):
  x_new = np.matmul(A, x)
  eigenvalue = x_new[0]/x[0]
  x = x_new
  print(eigenvalue, x)

1.0 [1 3 4 5]
71.0 [71 31 60 62]
14.309859154929578 [1016  552 1020 1062]
16.891732283464567 [17162  8910 16640 17272]
16.320708542127957 [280096 146672 273384 283912]
16.42731063635325 [4601224 2405424 4485216 4657464]
16.406639624586848 [75490624 39477552 73605472 76433672]
16.41061618460062 [1238847656  647811016 1207853760 1254259328]
16.409849870999796 [20329304048 10630607760 19820880288 20582410608]
16.40999748837049 [333603828368 174447847536 325260022208 337756663552]
16.40996904985494 [5474428498432 2862685040576 5337508710720 5542578427456]
16.40997452842627 [89835232216960 46976584610112 87588376256256 90953564391936]
16.40997347299514 [1474193777620672  770884519913280 1437322949028352 1492545599255744]
16.409973676320686 [24191481084550976 12650194639397440 23586431700642048 24492633930289280]
16.409973637150635 [396981566841109760 207589360663355136 387052722583086336
 401923477303403904]
16.409973644696628 [6514457049292982912 3406535937006692736 6351524976124015616
 65

Podemos ver que los vectores propios crecen de manera exponencial, por lo que se recomienda normalizarlos. 

In [16]:
x/np.linalg.norm(x)

array([-0.72072169, -0.04968346,  0.65948682,  0.20777133])

Comparándolo con el valor propio del método anterior, vemos que son iguales.

In [17]:
eigenvectors.T[0]/np.linalg.norm(eigenvectors.T[0])  

array([-0.55477694, -0.29010362, -0.5409015 , -0.5616832 ])