# Métodos iterativos

In [108]:
import numpy as np

A = np.random.randint(20, size=(5,5)) - 10
A += np.diag(np.diag(A)) * 5
x = np.random.randint(20, size=(5,1)) - 10
b = np.matmul(A,x)

print(f"Coeficientes:\n{A}")
print(f"Incognitas\n{x}")
print(f"Dependientes\n{b}")


Coeficientes:
[[-42  -7  -8  -9   1]
 [ -4   6  -2   1  -3]
 [  4  -8  54  -2  -2]
 [ -7  -1   6 -36  -3]
 [ -2   6  -5  -3 -42]]
Incognitas
[[ -1]
 [  1]
 [-10]
 [  6]
 [  4]]
Dependientes
[[  65]
 [  24]
 [-572]
 [-282]
 [-128]]


In [109]:
def StopByDiff(new_x, x, epsilon=0.01):
    '''
    Description: 
        Checks the difference between previous x values with current x values
    Inputs:
        new_x [vector]: with x values gotten from current iteration
        x [vector]: with x values from previous iteration
        epsilon: The minimum acceptable difference between new_x values and x
    Outputs:
        boolean If the difference between new_x and x is lesser than the epsilon
    '''
    diff = np.absolute(new_x - x)
    if (diff < epsilon).all():
        print("----Diff-----")
        print(diff)
        return True
    return False  

In [110]:
def StopByProduct(A, x, b, epsilon=0.01):
    '''
    Description:
        Checks the difference between the given x multiplied by the A matrix and the expected values b
    Input:
        A [matrix]: The coeficient matrix
        x [vector]: The calculated x values
        b [vector]: The expected dependent values
        epsilon: The minimum acceptable difference between real dependen values  and calculated dependent values
    Output:
        boolean If the difference between the real dependen values and the calculated dependent values is lesser than epsilon
    '''
    diff = np.absolute(b-np.matmul(A,x))
    if (diff < epsilon).all():
        print("---Product-----")
        print(diff)
        return True
    return False

In [111]:
def StopByDiagDominant(A):
    '''
    Description:
        Checks if the given matrix A has a dominant diagonal
    Input:
        A [vector]: The coeficient matrix
    Output:
        boolean If the matrix has or not a dominant diagonal
    '''
    abs_a = np.absolute(A).copy()
    diag = np.diag(abs_a)
    tot_y = abs_a.sum(axis=0)
    tot_x = abs_a.sum(axis=1)
    flag = True
    for i, diag_elem in enumerate(diag):
        #print(f"--{i}--")
        #print(f"{diag_elem} > ({tot_y[i]} - {diag_elem}) and {diag_elem} > ({tot_x[i]} - {diag_elem})")
        #print(f"{diag_elem} > ({tot_y[i] - diag_elem}) and {diag_elem} > ({tot_x[i] - diag_elem})")
        if (diag_elem <= (tot_y[i] - diag_elem) or diag_elem <= (tot_x[i] - diag_elem) ):
            flag = False
    
    if(flag):
        print("---DominantDiag-----")
        print(abs_a)
        return True
    return False
    

### Método de Jacobi

In [112]:
def jacobi(A, b, L=100, x=None):
    n = len(A[0])
    if x is None:
        x = np.zeros(n).reshape((n,1))
      
    print(f"Iteration 0")
    print(np.transpose(x))
    diag = np.diag(A).reshape((n,1))
    new_b = -A/diag + np.eye(n)
    c = b/diag
    # Método de paro k > L
    for k in range(1,L):
        old_x = x
        x = np.matmul(new_b,old_x) + c
        print(f"Iteration {k}")
        print(np.transpose(x))
        if StopByDiff(x, old_x) or StopByProduct(A, x, b) or StopByDiagDominant(A):
            return x

    return x

In [113]:
jacobi(A,b)

Iteration 0
[[0. 0. 0. 0. 0.]]
Iteration 1
[[ -1.54761905   4.         -10.59259259   7.83333333   3.04761905]]
Iteration 2
[[-1.8026581  -0.34435626 -9.48236332  6.0037478   4.39424288]]
Iteration 3
[[ -0.86595445   0.83393697 -10.12496734   6.24683485   3.78427981]]
Iteration 4
[[ -1.0065489    0.89870868 -10.03337884   5.97569724   3.96713959]]
Iteration 5
[[ -0.9723349    0.97212804 -10.01663817   6.00126227   3.99155125]]
Iteration 6
[[ -0.99265715   1.00846259 -10.00644461   5.99332593   3.99659148]]
Iteration 7
[[-0.99883388  1.00215512 -9.99966363  5.99754709  4.00210322]]
----Diff-----
[[0.00617674]
 [0.00630747]
 [0.00678098]
 [0.00422116]
 [0.00551174]]


array([[-0.99883388],
       [ 1.00215512],
       [-9.99966363],
       [ 5.99754709],
       [ 4.00210322]])

### Método Gauss-Seidel

In [114]:
def gauss_seidel(A,b,L=100,x=None):
    n = len(A[0])
    if x is None:
        x = np.zeros(n).reshape((n,1))

    print(f"Iteration 0")
    print(np.transpose(x))
    D = np.diag(A).reshape((n,1))
    B = -A/D + np.eye(n)
    c = b/D
    # Método de paro k > L
    for k in range(1,L):
        old_x = x.copy()
        for i in range(n):
            x[[i]] = np.matmul(B[i],x) + c[i]
        print(f"Iteration {k}")
        print(np.transpose(x))
        if StopByDiff(x, old_x) or StopByProduct(A, x, b) or StopByDiagDominant(A):
            return x
    
    return x

In [115]:
gauss_seidel(A,b)

Iteration 0
[[0. 0. 0. 0. 0.]]
Iteration 1
[[ -1.54761905   2.96825397 -10.03821282   6.37877229   4.28475022]]
Iteration 2
[[-1.39514942  0.80307584 -9.97532871  6.06268742  3.98326989]]
Iteration 3
[[-0.98570995  0.9989375  -9.99951381  5.9987261   3.99920085]]
Iteration 4
[[ -0.99966157   1.00020042 -10.00007216   5.9999832    4.00002231]]
Iteration 5
[[ -1.00001553   0.99997955 -10.00000168   6.00000145   3.99999791]]
----Diff-----
[[3.53954163e-04]
 [2.20872591e-04]
 [7.04804226e-05]
 [1.82516645e-05]
 [2.43924840e-05]]


array([[ -1.00001553],
       [  0.99997955],
       [-10.00000168],
       [  6.00000145],
       [  3.99999791]])