## Mitsiu Alejandro Carreño Sarabia E23S-18014

## Dependencia Lineal
Revisa si los siguientes conjuntos son linealmente independientes

    [2 1 5 2] [7 6 3 2] [9 4 0 6]
    
    
    
    [5 7 8 7] [3 1 3 1] [ 1 11 7 11]

In [1]:
import numpy as np
from numpy.linalg import LinAlgError
import sympy 

def independencia_lineal(vector, conjunto):
  A = np.array(conjunto).transpose()
  ind = np.array(vector).transpose()
  try:
    x = np.linalg.solve(A,ind)
  except LinAlgError:
    print("Matriz no cuadrada, intentando con minimos cuadrados ")
    x,res,rank,s = np.linalg.lstsq(A,ind,rcond=None)
    print(f"Rango {rank}")
  return x

def concunto_li(conjunto):
  c = conjunto[1:]
  vec =  conjunto[0]
  return independencia_lineal(vec, c)

e_one = np.array([[2,1,5,2],[7,6,3,2],[9,4,0,6]])

found_x = concunto_li(e_one)
#found_x = independencia_lineal(one[2], [one[0], one[1]])
print(found_x)

print("-------")

#(x[0]*b + x[1]*c ) - a
(found_x[0]*e_one[1] + found_x[1]*e_one[2] ) - e_one[0]

print("Ejercicio uno tiene una diferencia mayor a 0 por lo tanto es línealmente independiente")

'''
#Found on the internet, but must check
_, indexes = sympy.Matrix(e_one).T.rref()  # T is for transpose
print(indexes)

print(e_one[indexes,:])


if len(indexes) == 2:
    print("linearly independant")
else:
    print("linearly dependant") 
'''

Matriz no cuadrada, intentando con minimos cuadrados 
Rango 2
[ 0.56325394 -0.16362512]
-------
Ejercicio uno tiene una diferencia mayor a 0 por lo tanto es línealmente independiente


'\n#Found on the internet, but must check\n_, indexes = sympy.Matrix(e_one).T.rref()  # T is for transpose\nprint(indexes)\n\nprint(e_one[indexes,:])\n\n\nif len(indexes) == 2:\n    print("linearly independant")\nelse:\n    print("linearly dependant") \n'

In [2]:
e_two = np.array([[5,7,8,7],[3,1,3,1],[1,11,7,11]])
found_x = concunto_li(e_two)
print(found_x)

print("-"*10)
                
print((found_x[0]*e_two[1] + found_x[1]*e_two[2] ) - e_two[0])

print("Ejercicio dos tiene una diferencia muy cerca de 0 por lo tanto es línealmente dependiente")


Matriz no cuadrada, intentando con minimos cuadrados 
Rango 2
[1.5 0.5]
----------
[-3.55271368e-15  0.00000000e+00 -2.66453526e-15  0.00000000e+00]
Ejercicio dos tiene una diferencia muy cerca de 0 por lo tanto es línealmente dependiente


## Cantidad de soluciones

Calcula la cantidad de soluciones de los sistemas

    A = [[ -6 3 -8 -8 -2] [ 7 7 8 -1 -1] [ 2 -2 -9 8 6] [ 0 -10 -4 8 0] [ 6 4 -10 -1 0]]
    b = [[ 116] [ 26] [-117] [-132] [ -14]]
    A = [[ -2 4 -5 8 -6] [ 5 1 9 9 -2] [ -2 3 -6 1 -1] [ -7 2 -9 -5 1] [ -4 8 -10 16 -12]]
    b = [[ 21] [ 173] [ -66] [-179] [ 42]]
    A = [[-10 1 5 -1 2] [ -8 -10 -7 -6 6] [ 5 -5 -8 -6 6] [-10 -7 5 1 9] [-20 2 10 -2 4]]
    b = [[110] [116] [-59] [100] [ -4]]

In [3]:
def num_sols(A, b):
    r_a = np.linalg.matrix_rank(A)
    r_b = np.linalg.matrix_rank(b)
    print(r_a, r_b)
    if(r_a != r_b):
        print("Sistema inconsistente, no tiene solucion")
    elif (r_a == len(A[0])):
        print("Solución única")
    elif (r_a < len(A[0])):
        print("Soluciones infinitas")
    else:
        print("Err, esto no debería de pasar")
        
    try:
        solve = np.linalg.solve(A,b)
        return solve
    except:
        print("El sistema no se puede calcular")
        
        
a_one = np.array([[ -6,3,-8,-8,-2], [ 7,7,8,-1,-1], [ 2,-2,-9,8,6], [ 0,-10,-4,8,0], [ 6,4,-10,-1,0]])
b_one = np.array([[ 116], [ 26], [-117], [-132], [ -14]])
B_one = np.concatenate([a_one,b_one],1)

x_one = num_sols(a_one, B_one)
print(x_one)

a_two = np.array([[ -2,4,-5,8,-6],[ 5,1,9,9,-2],[ -2,3,-6,1,-1],[ -7,2,-9,-5,1],[ -4,8,-10,16,-12]])
b_two = np.array([[ 21], [ 173], [ -66], [-179], [ 42]])
B_two = np.concatenate([a_two,b_two],1)

x_two = num_sols(a_two, B_two)
print(x_two)

a_three = np.array([[-10,1,5,-1,2],[ -8,-10,-7,-6,6],[ 5,-5,-8,-6,6],[-10,-7,5,1,9],[-20,2,10,-2,4]])
b_three = np.array([[110],[116],[-59],[100],[ -4]])
B_three = np.concatenate([a_three,b_three],1)

x_three = num_sols(a_three, B_three)
print(x_three)

5 5
Solución única
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -1.25369974e-16
   0.00000000e+00 -7.00000000e+00]
 [-0.00000000e+00  1.00000000e+00 -0.00000000e+00  1.88698404e-16
  -0.00000000e+00  8.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00 -2.76568013e-17
  -0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00 -6.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
   1.00000000e+00 -5.00000000e+00]]
4 4
Soluciones infinitas
El sistema no se puede calcular
None
4 5
Sistema inconsistente, no tiene solucion
El sistema no se puede calcular
None


## Vectores ortogonales

Encuentra si los siguientes conjuntos de vectores son ortogonales

    [[1,2,3],[4,5,6]]
    [[1,0,-1],[1,√2,-1],[1,-√2,1]]

In [4]:

def es_ortogonal(v1,v2):
  return np.matmul(v1,v2.transpose()) == 0

or_one = np.array([1,2,3])
or_two = np.array([4,5,6])

print(es_ortogonal(or_one, or_two))

or_three = np.array([1,0,-1])
or_four = np.array([1, np.sqrt(2), -1])
or_five = np.array([1, -1*np.sqrt(2), 1])

if es_ortogonal(or_three, or_four):
    print(es_ortogonal(or_four, or_five))
else:
    print(False)

False
False
