# Mitsiu Alejandro Carreño Sarabia - E23S-18014

Experimenta que sucede cuando calculas vectores y valores propios en matrices 

    no son linealmente independientes
    están mal condicionadas
    diagonales
    tridiagonaes
    tringulares

In [1]:
import numpy as np

def GetEigenVs(A):
    eigenvals, eigenvecs = np.linalg.eig(A)
    
    print("Valores propios")
    for eigenval in eigenvals:
        print(eigenval)
        
    print("Vectores propios")
    for eigenvec in eigenvecs.T:
        print(eigenvec)
        
    print("Comprobando")
    for eigenval, eigenvec in zip(eigenvals, eigenvecs.T):
        print(f"{np.matmul(A, eigenvec)} - {eigenval * eigenvec} = \n \
            {(np.matmul(A, eigenvec) - (eigenval * eigenvec))}")
        

## No son linealmente independientes

In [2]:
a_1 = np.random.randint(10, size=(3))
b_1 = np.random.randint(10, size=(3))
c_1 = a_1+5*b_1
print("Matriz")
print([a_1, b_1, c_1])

GetEigenVs(np.array([a_1, b_1, c_1]))
## Podemos observar que las variaciones estan dentro del rango usual de los errores máquina

Matriz
[array([4, 7, 3]), array([3, 6, 2]), array([19, 37, 13])]
Valores propios
22.912712210513316
-6.412842594192754e-15
0.08728778948667838
Vectores propios
[-0.2092642  -0.15136187 -0.96607354]
[-0.78446454  0.19611614  0.58834841]
[ 0.83775115 -0.2632333  -0.47841535]
Comprobando
[ -4.79481049  -3.46811089 -22.13536492] - [ -4.79481049  -3.46811089 -22.13536492] = 
             [ 1.77635684e-15 -2.66453526e-15 -1.42108547e-14]
[ 4.77395901e-15 -2.22044605e-16  4.32986980e-15] - [ 5.03064762e-15 -1.25766190e-15 -3.77298571e-15] = 
             [-2.56688613e-16  1.03561730e-15  8.10285551e-15]
[ 0.07312545 -0.02297705 -0.04175982] - [ 0.07312545 -0.02297705 -0.04175982] = 
             [ 2.77555756e-17 -1.26287869e-15 -9.90180160e-15]


## Mal condicionadas

In [5]:
a_2 = np.random.randint(10, size=(4,3)).astype(float)
x_2 = np.random.randint(10, size=(3,1)).astype(float)
b_2 = np.matmul(a_2, x_2)
a_2[-1] = a_2[0]*4
a_2[-1][0] += 0.000000001
m_2 = np.concatenate([a_2, b_2], 1)
print("Matriz")
print(m_2)

## Podemos observar que las variaciones estan dentro del rango usual de los errores máquina 
GetEigenVs(m_2)

Matriz
[[ 5.  1.  9. 66.]
 [ 3.  5.  7. 80.]
 [ 0.  5.  4. 59.]
 [20.  4. 36. 52.]]
Valores propios
(96.57915163493871+0j)
(-32.39848415603561+0j)
(0.9096662605484818+1.5571273892211843j)
(0.9096662605484818-1.5571273892211843j)
Vectores propios
[-0.45968796+0.j -0.54808324+0.j -0.39635807+0.j -0.57549285+0.j]
[ 0.49145524+0.j  0.62769429+0.j  0.48858871+0.j -0.35461627+0.j]
[ 0.77142823+0.j          0.1234336 -0.418472j   -0.46220141+0.01518547j
  0.01334818+0.02246992j]
[ 0.77142823-0.j          0.1234336 +0.418472j   -0.46220141-0.01518547j
  0.01334818-0.02246992j]
Comprobando
[-44.39627358+0.j -52.93341431+0.j -38.27992643+0.j -55.58061088+0.j] - [-44.39627358+0.j -52.93341431+0.j -38.27992643+0.j -55.58061088+0.j] = 
             [3.55271368e-14+0.j 1.06581410e-13+0.j 2.13162821e-14+0.j
 2.13162821e-14+0.j]
[-15.92240488+0.j -20.33634341+0.j -15.82953361+0.j  11.48902958+0.j] - [-15.92240488+0.j -20.33634341+0.j -15.82953361+0.j  11.48902958-0.j] = 
             [-3.55271368e-15+

## Diagonales

In [6]:
m_3 = np.diag(np.random.randint(10, size=4))
print("Matriz")
print(m_3)

## Podemos observar que las variaciones estan dentro del rango usual de los errores máquina
## y que los vectores propios estan compuestos de un único 1 por vector 
GetEigenVs(m_3)

Matriz
[[0 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 5]]
Valores propios
0.0
6.0
1.0
5.0
Vectores propios
[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]
Comprobando
[0. 0. 0. 0.] - [0. 0. 0. 0.] = 
             [0. 0. 0. 0.]
[0. 6. 0. 0.] - [0. 6. 0. 0.] = 
             [0. 0. 0. 0.]
[0. 0. 1. 0.] - [0. 0. 1. 0.] = 
             [0. 0. 0. 0.]
[0. 0. 0. 5.] - [0. 0. 0. 5.] = 
             [0. 0. 0. 0.]


## Tridiagonales

In [7]:
a_4 = np.concatenate((np.array([0]), np.random.randint(10, size=4)+1))
b_4 = np.random.randint(10, size=5) +1
c_4 = np.concatenate((np.random.randint(10, size=4)+1, np.array([0])))

m_4 = np.diag(a_4[1:], -1) + np.diag(b_4, 0) + np.diag(c_4[:-1], 1)

print("Matriz")
print(m_4)

## Podemos observar que las variaciones estan dentro del rango usual de los errores máquina
GetEigenVs(m_4)

Matriz
[[ 2  7  0  0  0]
 [ 6  1  8  0  0]
 [ 0  1  7  6  0]
 [ 0  0 10  3  7]
 [ 0  0  0  5  9]]
Valores propios
-6.087716677597932
-3.8798479745237078
15.704421020983672
6.904232139673465
9.358911491464468
Vectores propios
[ 0.62122432 -0.71775518  0.16998743 -0.25116537  0.08323505]
[ 0.68405528 -0.57459158 -0.16255152  0.39052123 -0.15160165]
[0.1678588  0.32862966 0.47814451 0.63889024 0.47646936]
[-0.78310962 -0.54865019  0.18241245  0.08853016 -0.21121174]
[-0.6309945  -0.66334753 -0.21986203  0.02411874  0.33599847]
Comprobando
[-3.78183765  4.3694902  -1.03483534  1.52902358 -0.50671139] - [-3.78183765  4.3694902  -1.03483534  1.52902358 -0.50671139] = 
             [ 2.66453526e-15 -1.77635684e-15 -6.66133815e-16 -2.66453526e-15
  0.00000000e+00]
[-2.6540305   2.22932798  0.63067517 -1.515163    0.58819134] - [-2.6540305   2.22932798  0.63067517 -1.515163    0.58819134] = 
             [ 3.10862447e-15 -2.66453526e-15  0.00000000e+00  1.55431223e-15
  2.44249065e-15]
[ 2.6361

## Triangulares

In [9]:
m_5 = np.triu(np.random.randint(10, size=(4,4)))

print("Matriz")
print(m_5)

## Podemos observar que las variaciones estan dentro del rango usual de los errores máquina
## y que los vectores propios generan una matriz triangular de orientación inversa
## la matriz es un triangular superior y el conjunto de vectores propios genera un triangular inferior
GetEigenVs(m_5)

Matriz
[[7 7 6 4]
 [0 2 5 0]
 [0 0 9 5]
 [0 0 0 0]]
Valores propios
7.0
2.0
9.0
0.0
Vectores propios
[1. 0. 0. 0.]
[-0.81373347  0.58123819  0.          0.        ]
[0.97593535 0.12674485 0.17744279 0.        ]
[-0.6362974   0.59546548 -0.23818619  0.42873514]
Comprobando
[7. 0. 0. 0.] - [7. 0. 0. 0.] = 
             [0. 0. 0. 0.]
[-1.62746694  1.16247639  0.          0.        ] - [-1.62746694  1.16247639  0.          0.        ] = 
             [0. 0. 0. 0.]
[8.78341811 1.14070365 1.59698511 0.        ] - [8.78341811 1.14070365 1.59698511 0.        ] = 
             [0. 0. 0. 0.]
[ 0.00000000e+00 -2.22044605e-16 -4.44089210e-16  0.00000000e+00] - [-0.  0. -0.  0.] = 
             [ 0.00000000e+00 -2.22044605e-16 -4.44089210e-16  0.00000000e+00]
